project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "Milan's Lab Journal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "01 Company Segment"
            file: content/01_journal/01_Company_Segmentation.qmd
          # - text: "02 --"
          #   file: content/01_journal/02_Regression.qmd
          - text: "03 H20"
            file: content/01_journal/03_h20.qmd
          # - text: "04 --"
          #   file: content/01_journal/04_data_visualization.qmd
      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto